import * as THREE from 'https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.module.js';

/**
 * InputController manages user click/tap interactions with the terrain
 * and sets target points for the camera to glide towards.
 */
class InputController {
    constructor(camera, scene, container) {
        this.camera = camera;
        this.scene = scene;
        this.container = container;

        this.raycaster = new THREE.Raycaster();
        this.mouse = new THREE.Vector2();

        // Target camera position and target look-at point
        this.targetCameraPosition = camera.position.clone();
        this.targetLookAt = new THREE.Vector3(0, 0, 0);
        this.currentLookAt = new THREE.Vector3(0, 0, 0);

        // Track user interaction to determine idle state
        this.lastInteractionTime = performance.now();
        this.idleDriftSpeed = 15; // Speed of auto drift when idle (units/sec)

        this.initEvents();
    }

    initEvents() {
        const handleTrigger = (clientX, clientY) => {
            // Calculate mouse position in normalized device coordinates (-1 to +1)
            const rect = this.container.getBoundingClientRect();
            this.mouse.x = ((clientX - rect.left) / rect.width) * 2 - 1;
            this.mouse.y = -((clientY - rect.top) / rect.height) * 2 + 1;

            this.raycaster.setFromCamera(this.mouse, this.camera);

            // Collect all terrain meshes from the scene
            const terrainMeshes = [];
            this.scene.traverse((object) => {
                // Terrain meshes have colors/positions generated by meshBuilder
                if (object.isMesh && object.geometry && object.geometry.attributes.position) {
                    terrainMeshes.push(object);
                }
            });

            // Raycast against terrain meshes
            const intersects = this.raycaster.intersectObjects(terrainMeshes);
            if (intersects.length > 0) {
                const intersectPoint = intersects[0].point;

                // Click sets the target look-at point on the terrain
                this.targetLookAt.copy(intersectPoint);

                // Set camera target position to be offset from the target point (above and behind the camera's current angle)
                // Let's glide the camera to look down at the terrain from a nice vantage point:
                // Camera target = intersectPoint + (vantage offset)
                const offset = new THREE.Vector3(0, 100, 160);
                this.targetCameraPosition.copy(intersectPoint).add(offset);

                this.lastInteractionTime = performance.now();
            }
        };

        // Mouse click
        this.container.addEventListener('click', (e) => {
            // Only trigger if pointer lock is not active or if we just clicked
            handleTrigger(e.clientX, e.clientY);
        });

        // Touch tap
        this.container.addEventListener('touchstart', (e) => {
            if (e.touches.length > 0) {
                handleTrigger(e.touches[0].clientX, e.touches[0].clientY);
            }
        }, { passive: true });
    }

    /**
     * Updates camera glide and idle drift interpolation
     */
    update(camera, delta) {
        const now = performance.now();
        const timeSinceLastInteraction = now - this.lastInteractionTime;

        // If idle for more than 4 seconds, apply slow automatic drift
        if (timeSinceLastInteraction > 4000) {
            // Apply drift to the target position: drift slowly in the direction the camera is looking (forward)
            const forward = new THREE.Vector3(0, 0, -1).applyQuaternion(camera.quaternion);
            forward.y = 0; // Keep drift horizontal
            forward.normalize();
            
            // Drift the camera target forward
            this.targetCameraPosition.addScaledVector(forward, this.idleDriftSpeed * delta);
            // Slowly rotate or nudge look target
            this.targetLookAt.addScaledVector(forward, this.idleDriftSpeed * delta);
        }

        // Smoothly glide camera position to target position using easing interpolation
        // lerp factor is delta-independent for consistency
        const easeFactor = 1.0 - Math.exp(-3 * delta); // Smooth easing
        camera.position.lerp(this.targetCameraPosition, easeFactor);

        // Smoothly glide lookAt position
        this.currentLookAt.lerp(this.targetLookAt, easeFactor);
        camera.lookAt(this.currentLookAt);
    }
}

export { InputController };
